export const aboutData = {
  name: "Tayler Ramsay",
  title: "Senior Full-Stack UX Engineer",
  location: "United States",
  bio: [
    "I'm a designer who codes and a developer who designs. With over 8 years of experience, I specialize in building products that are both beautiful and functional.",
    "My sweet spot is at the intersection of design and engineering—turning complex problems into intuitive interfaces that users love.",
  ],
  currentRole: {
    company: "Synchrony",
    title: "Senior UX Engineer",
  },
  skills: [
    "UX Research",
    "Prototyping",
    "Design Systems",
    "React",
    "Next.js",
    "TypeScript",
    "Node.js",
    "Python",
    "Figma",
    "Framer",
  ],
  tools: [
    "Figma",
    "React",
    "Next.js",
    "TypeScript",
    "Node.js",
    "PostgreSQL",
    "Tailwind CSS",
    "Framer Motion",
  ],
  experience: [
    {
      company: "Synchrony",
      role: "Senior UX Engineer",
      period: "Current",
      type: "current",
    },
    {
      company: "Rayni AI",
      role: "Founding Engineer",
      period: "2023-2024",
      type: "recent",
    },
    {
      company: "Versatile Credit",
      role: "Lead UX Engineer",
      period: "2019-2023",
      type: "previous",
    },
  ],
};
