[build]
  publish = "public"
  command = "echo 'Static site - no build needed'"

[functions]
  directory = "netlify/functions"

# API routes only
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA fallback for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for iframe embedding
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "frame-ancestors 'self' localhost:* *.netlify.app *.vercel.app"